import { parkBuildings, parkCompanies } from "@/data/workorders";
import { leafMenus } from "@/menus";
import { rows } from "./present";
import type { ResourceDef, SeedRow } from "./types";

const buildingNames = [...parkBuildings, "海纳楼裙房", "旧传达室"];
const companyNames = [
  ...parkCompanies.filter((name) => name !== "园区公共"),
  "南湾新材料有限公司",
  "汇川检测技术有限公司",
];
const hostCompanies = [...companyNames, "园区物业服务中心"];
const zones = ["海纳片区", "星河片区", "云启片区", "科创片区", "公共配套"];
const menuGroups = [...new Set(leafMenus().map((item) => item.group ?? "首页"))];

function menuSeed(): SeedRow[] {
  const live = leafMenus().map((item, index) => ({
    createdAt: "2026-09-01 09:00",
    updatedAt: "2026-10-02 11:00",
    fields: {
      name: item.title,
      route: item.path ?? "",
      group: item.group ?? "首页",
      sort: String((index + 1) * 10),
      visible: "显示",
      remark: "对照当前侧栏。改动只保存在本机，不会改变左侧导航。",
    },
  }));
  live.push({
    createdAt: "2026-08-12 10:00",
    updatedAt: "2026-09-30 15:00",
    fields: {
      name: "旧版报表",
      route: "/legacy/report",
      group: "系统设置",
      sort: "990",
      visible: "隐藏",
      remark: "历史入口，只在台账里保留。",
    },
  });
  return live;
}

export const resources: ResourceDef[] = [
  {
    key: "park-info",
    title: "园区信息",
    noun: "园区档案",
    group: "园区管理",
    path: "/park/info",
    description: "维护临港智慧园区的名称、地址、面积和运营主体。档案保存在本机。",
    codePrefix: "YQ-202610",
    storageKey: "park-campus-park-info-v1",
    nameField: "name",
    createLabel: "新建档案",
    stats: [
      { label: "在营", field: "status", equals: "在营", tone: "green" },
      { label: "筹开", field: "status", equals: "筹开", tone: "orange" },
      { label: "停用", field: "status", equals: "停用", tone: "red" },
      { label: "档案数", tone: "blue" },
    ],
    fields: [
      { key: "name", label: "园区名称", kind: "text", required: true, list: true, width: 180, search: true, span: 12 },
      { key: "zone", label: "分区", kind: "select", required: true, list: true, filter: true, options: ["主园区", "东区", "西区", "滨海配套"] },
      { key: "address", label: "地址", kind: "text", required: true, list: true, width: 260, search: true, span: 16 },
      { key: "area", label: "占地面积", kind: "number", required: true, list: true, suffix: "㎡", width: 120 },
      { key: "operator", label: "运营主体", kind: "text", required: true, list: true, width: 200, search: true, span: 12 },
      { key: "openedAt", label: "启用日期", kind: "date", required: true, list: true, width: 120 },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["在营", "筹开", "停用"] },
      { key: "contact", label: "联系人", kind: "text", required: true, search: true },
      { key: "phone", label: "电话", kind: "text", required: true, search: true },
      { key: "summary", label: "简介", kind: "textarea", placeholder: "区位、主导产业、配套" },
    ],
    seed: rows(
      ["name", "zone", "address", "area", "operator", "openedAt", "status", "contact", "phone", "summary"],
      [
        ["临港智慧园区", "主园区", "上海市浦东新区海港大道 1888 号", "186000", "临港园区运营有限公司", "2019-06-18", "在营", "林知夏", "021-50880001", "面向智能制造与研发办公的综合园区，海纳、星河、云启三片区已投入使用。"],
        ["海纳片区", "东区", "海港大道 1888 号东侧", "62000", "临港园区运营有限公司", "2019-06-18", "在营", "周启明", "021-50880021", "研发办公为主，星澜智造与东岸半导体在此入驻。"],
        ["星河片区", "西区", "海港大道 1888 号西侧", "54000", "临港园区运营有限公司", "2020-11-02", "在营", "周启明", "021-50880022", "云计算与设计企业集中，公共会议室在 3 层。"],
        ["滨海配套区", "滨海配套", "海港大道 1900 号", "28000", "临港园区运营有限公司", "2026-12-01", "筹开", "林知夏", "021-50880031", "商业配套与访客中心仍在筹开，暂不对外出租。"],
        ["旧闸口用地", "东区", "海港大道 1860 号", "4200", "临港园区运营有限公司", "2016-05-01", "停用", "马俊", "021-50880041", "原传达与闸口用地，已退出日常运营。"],
      ],
    ),
  },
  {
    key: "buildings",
    title: "楼宇管理",
    noun: "楼宇",
    group: "园区管理",
    path: "/park/buildings",
    description: "楼栋台账、层数、用途和启用状态。示例楼宇与报修、缴费里的名称一致。",
    codePrefix: "LY-202610",
    storageKey: "park-campus-buildings-v1",
    nameField: "name",
    createLabel: "新建楼宇",
    stats: [
      { label: "启用", field: "status", equals: "启用", tone: "green" },
      { label: "装修中", field: "status", equals: "装修中", tone: "orange" },
      { label: "停用", field: "status", equals: "停用", tone: "red" },
      { label: "楼宇数", tone: "blue" },
    ],
    fields: [
      { key: "name", label: "楼宇名称", kind: "text", required: true, list: true, width: 160, search: true, span: 12 },
      { key: "zone", label: "片区", kind: "select", required: true, list: true, filter: true, options: zones },
      { key: "floors", label: "层数", kind: "number", required: true, list: true, suffix: "层", width: 90 },
      { key: "area", label: "建筑面积", kind: "number", required: true, list: true, suffix: "㎡", width: 130 },
      { key: "usage", label: "用途", kind: "select", required: true, list: true, filter: true, options: ["研发办公", "生产实验", "配套商业", "公共配套"] },
      { key: "manager", label: "楼宇管家", kind: "text", required: true, list: true, search: true },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["启用", "装修中", "停用"] },
      { key: "builtAt", label: "竣工日期", kind: "date", required: true },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "zone", "floors", "area", "usage", "manager", "status", "builtAt", "remark"],
      [
        ["海纳楼", "海纳片区", "18", "42800", "研发办公", "周启明", "启用", "2019-06-18", "客梯本周检修，报修工单仍在跟进。"],
        ["星河楼", "星河片区", "22", "51600", "研发办公", "周启明", "启用", "2020-11-02", "6 层为浦江云算机房，夜间需值守。"],
        ["云启楼", "云启片区", "12", "36200", "生产实验", "马俊", "启用", "2021-04-16", "5 层实验室有独立冷量回路。"],
        ["科创中心", "科创片区", "8", "18400", "研发办公", "林知夏", "启用", "2018-09-01", "瀚海物流使用 4 层仓储办公。"],
        ["园区公共区", "公共配套", "3", "9600", "公共配套", "马俊", "启用", "2019-06-18", "含中央大堂、景观和地下公共停车。"],
        ["海纳楼裙房", "海纳片区", "4", "6200", "配套商业", "周启明", "装修中", "2024-03-08", "南湾新材料计划十月下旬入驻。"],
        ["旧传达室", "公共配套", "1", "280", "公共配套", "马俊", "停用", "2016-05-01", "已封闭，不再排班。"],
      ],
    ),
  },
  {
    key: "spaces",
    title: "空间房间",
    noun: "房间",
    group: "园区管理",
    path: "/park/spaces",
    description: "房间、实验室和公共空间的空置、出租与自用情况。",
    codePrefix: "KJ-202610",
    storageKey: "park-campus-spaces-v1",
    nameField: "name",
    createLabel: "新建房间",
    stats: [
      { label: "空置", field: "status", equals: "空置", tone: "blue" },
      { label: "已出租", field: "status", equals: "已出租", tone: "purple" },
      { label: "装修", field: "status", equals: "装修", tone: "orange" },
      { label: "房间数", tone: "green" },
    ],
    fields: [
      { key: "name", label: "房间", kind: "text", required: true, list: true, width: 140, search: true },
      { key: "building", label: "楼宇", kind: "select", required: true, list: true, filter: true, options: buildingNames },
      { key: "floor", label: "楼层", kind: "text", required: true, list: true, width: 90, placeholder: "例如 12F" },
      { key: "area", label: "面积", kind: "number", required: true, list: true, suffix: "㎡", width: 110 },
      { key: "kind", label: "类型", kind: "select", required: true, list: true, filter: true, options: ["办公室", "实验室", "会议室", "工位区", "公共空间", "仓库"] },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["空置", "已出租", "自用", "装修"] },
      { key: "tenant", label: "使用方", kind: "text", list: true, width: 200, search: true, placeholder: "空置可留空" },
      { key: "rent", label: "参考月租", kind: "money", required: true, list: true, width: 130 },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "building", "floor", "area", "kind", "status", "tenant", "rent", "remark"],
      [
        ["1206", "海纳楼", "12F", "860", "办公室", "已出租", "星澜智造（上海）有限公司", "18600", "主办公区，含两间洽谈室。"],
        ["1502", "海纳楼", "15F", "640", "办公室", "已出租", "东岸半导体有限公司", "16800", "靠近客梯，检修期间改走货梯。"],
        ["801", "海纳楼", "8F", "420", "办公室", "空置", "", "12800", "朝东，可下周带看。"],
        ["608", "星河楼", "6F", "980", "办公室", "已出租", "浦江云算科技有限公司", "22400", "含独立机房隔间。"],
        ["1901", "星河楼", "19F", "210", "办公室", "已出租", "青禾设计工作室", "6800", "小开间，合同十月中到期。"],
        ["星河会议室", "星河楼", "3F", "80", "会议室", "自用", "园区物业", "0", "企业可预约，装修协议即将到期。"],
        ["云启实验室", "云启楼", "5F", "1200", "实验室", "已出租", "临港生物医药有限公司", "31000", "独立冷量与废液暂存。"],
        ["901", "云启楼", "9F", "360", "办公室", "已出租", "澜桥咨询有限公司", "9600", ""],
        ["208", "云启楼", "2F", "540", "仓库", "装修", "", "7000", "汇川检测退租后整修。"],
        ["408", "科创中心", "4F", "760", "仓库", "已出租", "瀚海物流（临港）有限公司", "11200", "轻仓储，夜间有人值守。"],
        ["中央大堂", "园区公共区", "1F", "1600", "公共空间", "自用", "园区物业", "0", "访客报到与公告屏所在位置。"],
        ["公共工位", "星河楼", "2F", "300", "工位区", "空置", "", "9000", "可按工位拆分。"],
      ],
    ),
  },
  {
    key: "companies",
    title: "入驻企业",
    noun: "企业",
    group: "企业服务",
    path: "/enterprise/companies",
    description: "在园企业名录、联系人和入驻状态。名称与报修、缴费示例保持一致。",
    codePrefix: "QY-202610",
    storageKey: "park-campus-companies-v1",
    nameField: "name",
    createLabel: "新建企业",
    stats: [
      { label: "在园", field: "status", equals: "在园", tone: "green" },
      { label: "即将入驻", field: "status", equals: "即将入驻", tone: "orange" },
      { label: "退租办理", field: "status", equals: "退租办理", tone: "red" },
      { label: "企业数", tone: "blue" },
    ],
    fields: [
      { key: "name", label: "企业名称", kind: "text", required: true, list: true, width: 220, search: true, span: 16 },
      { key: "industry", label: "行业", kind: "select", required: true, list: true, filter: true, options: ["智能制造", "云计算", "生物医药", "物流仓储", "设计服务", "半导体", "专业服务"] },
      { key: "building", label: "楼宇", kind: "select", required: true, list: true, filter: true, options: buildingNames },
      { key: "room", label: "房间", kind: "text", required: true, list: true, search: true },
      { key: "contact", label: "联系人", kind: "text", required: true, list: true, search: true },
      { key: "phone", label: "电话", kind: "text", required: true, search: true },
      { key: "status", label: "入驻状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 110, options: ["在园", "即将入驻", "退租办理"] },
      { key: "enteredAt", label: "入驻日期", kind: "date", required: true, width: 120 },
      { key: "staff", label: "在园人数", kind: "number", required: true, list: true, suffix: "人", width: 110 },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "industry", "building", "room", "contact", "phone", "status", "enteredAt", "staff", "remark"],
      [
        ["星澜智造（上海）有限公司", "智能制造", "海纳楼", "12F-1206", "顾清和", "13816220018", "在园", "2022-03-01", "186", "本周有扩租来访。"],
        ["浦江云算科技有限公司", "云计算", "星河楼", "6F-608", "沈知远", "13917008821", "在园", "2021-07-15", "142", "机房参观需提前一天预约。"],
        ["临港生物医药有限公司", "生物医药", "云启楼", "5F 实验室", "许南星", "13701886620", "在园", "2023-01-09", "96", ""],
        ["瀚海物流（临港）有限公司", "物流仓储", "科创中心", "4F-408", "曹野", "13601775530", "在园", "2020-11-20", "64", "夜间有自有值守。"],
        ["青禾设计工作室", "设计服务", "星河楼", "19F-1901", "叶小满", "15021006648", "在园", "2024-05-06", "12", "租赁将于 10 月 15 日到期。"],
        ["东岸半导体有限公司", "半导体", "海纳楼", "15F-1502", "梁川", "13162550019", "在园", "2022-09-12", "210", "总部审计人员 10 月 4 日到访。"],
        ["澜桥咨询有限公司", "专业服务", "云启楼", "9F-901", "宋晚晴", "18621660027", "在园", "2025-02-18", "28", ""],
        ["南湾新材料有限公司", "智能制造", "海纳楼裙房", "待分配", "江衡", "13918660041", "即将入驻", "2026-10-20", "0", "裙房装修完成后再发钥匙。"],
        ["汇川检测技术有限公司", "专业服务", "云启楼", "2F-208", "裴宁", "13764550083", "退租办理", "2021-04-01", "8", "场地移交后进入装修。"],
      ],
    ),
  },
  {
    key: "contracts",
    title: "合同管理",
    noun: "合同",
    group: "企业服务",
    path: "/enterprise/contracts",
    description: "租赁、物业、停车和装修合同的签订与到期提醒。此处只保留摘要，没有合同扫描件。",
    codePrefix: "HT-202610",
    storageKey: "park-campus-contracts-v1",
    nameField: "title",
    createLabel: "新建合同",
    stats: [
      { label: "即将到期", field: "status", equals: "即将到期", tone: "orange" },
      { label: "履行中", field: "status", equals: "履行中", tone: "green" },
      { label: "草稿", field: "status", equals: "草稿", tone: "blue" },
      { label: "合同数", tone: "purple" },
    ],
    fields: [
      { key: "title", label: "合同名称", kind: "text", required: true, list: true, width: 220, search: true, span: 16 },
      { key: "company", label: "签约企业", kind: "select", required: true, list: true, filter: true, search: true, width: 200, options: companyNames },
      { key: "type", label: "类型", kind: "select", required: true, list: true, filter: true, options: ["租赁合同", "物业服务合同", "停车协议", "装修协议"] },
      { key: "building", label: "楼宇", kind: "select", required: true, options: buildingNames },
      { key: "room", label: "房间", kind: "text", required: true, search: true },
      { key: "startAt", label: "开始日期", kind: "date", required: true },
      { key: "endAt", label: "结束日期", kind: "date", required: true, list: true, width: 120 },
      { key: "amount", label: "合同金额", kind: "money", required: true, list: true, width: 140 },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 110, options: ["草稿", "履行中", "即将到期", "已终止"] },
      { key: "owner", label: "经办人", kind: "text", required: true, list: true, search: true },
      { key: "remark", label: "摘要", kind: "textarea", placeholder: "租期、付款节奏或特殊约定" },
    ],
    seed: rows(
      ["title", "company", "type", "building", "room", "startAt", "endAt", "amount", "status", "owner", "remark"],
      [
        ["星澜智造租赁合同", "星澜智造（上海）有限公司", "租赁合同", "海纳楼", "12F-1206", "2024-04-01", "2027-03-31", "2460000", "履行中", "陈予安", "按季支付，含 12 个车位。"],
        ["浦江云算租赁合同", "浦江云算科技有限公司", "租赁合同", "星河楼", "6F-608", "2023-08-01", "2026-10-31", "1980000", "即将到期", "陈予安", "到期前需确认是否续租机房隔间。"],
        ["临港生物实验室租赁", "临港生物医药有限公司", "租赁合同", "云启楼", "5F 实验室", "2025-01-01", "2027-12-31", "3600000", "履行中", "陈予安", "冷量另按表计结算。"],
        ["瀚海仓储租赁", "瀚海物流（临港）有限公司", "租赁合同", "科创中心", "4F-408", "2024-01-01", "2026-12-31", "860000", "履行中", "周启明", ""],
        ["青禾设计工位租赁", "青禾设计工作室", "租赁合同", "星河楼", "19F-1901", "2024-05-06", "2026-10-15", "96000", "即将到期", "陈予安", "企业希望缩租到公共工位。"],
        ["澜桥咨询物业服务", "澜桥咨询有限公司", "物业服务合同", "云启楼", "9F-901", "2026-01-01", "2026-12-31", "128000", "履行中", "陈予安", "与租赁分开签订。"],
        ["南湾新材料租赁草案", "南湾新材料有限公司", "租赁合同", "海纳楼裙房", "待分配", "2026-11-01", "2029-10-31", "720000", "草稿", "陈予安", "待裙房竣工验收后盖章。"],
        ["汇川检测退租协议", "汇川检测技术有限公司", "租赁合同", "云启楼", "2F-208", "2021-04-01", "2026-09-30", "240000", "已终止", "周启明", "场地已移交，装修中。"],
        ["东岸半导体停车协议", "东岸半导体有限公司", "停车协议", "园区公共区", "地下车位", "2025-01-01", "2026-12-31", "186000", "履行中", "陈予安", "固定 40 个车位。"],
        ["星河会议室装修协议", "青禾设计工作室", "装修协议", "星河楼", "3F 会议室", "2026-09-01", "2026-10-20", "45000", "即将到期", "周启明", "围挡拆除前不可预约。"],
      ],
    ),
  },
  {
    key: "visitors",
    title: "访客通行",
    noun: "访客",
    group: "通行安防",
    path: "/visitors",
    description: "访客预约、审核和到离记录。闸机尚未接入，状态由前台在本机更新。",
    codePrefix: "FK-202610",
    storageKey: "park-campus-visitors-v1",
    nameField: "name",
    createLabel: "登记访客",
    stats: [
      { label: "待审核", field: "status", equals: "待审核", tone: "orange" },
      { label: "已通过", field: "status", equals: "已通过", tone: "green" },
      { label: "已到访", field: "status", equals: "已到访", tone: "blue" },
      { label: "访客数", tone: "purple" },
    ],
    fields: [
      { key: "name", label: "访客姓名", kind: "text", required: true, list: true, width: 120, search: true },
      { key: "company", label: "来访单位", kind: "text", required: true, list: true, width: 180, search: true },
      { key: "hostCompany", label: "被访企业", kind: "select", required: true, list: true, filter: true, width: 200, options: hostCompanies },
      { key: "host", label: "被访人", kind: "text", required: true, list: true, search: true },
      { key: "purpose", label: "事由", kind: "text", required: true, search: true, span: 16 },
      { key: "visitDate", label: "到访日期", kind: "date", required: true, list: true, width: 120 },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["待审核", "已通过", "已到访", "已离开", "已拒绝"] },
      { key: "plate", label: "车牌", kind: "text", list: true, search: true, placeholder: "无车辆可留空" },
      { key: "phone", label: "手机", kind: "text", required: true, search: true },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "company", "hostCompany", "host", "purpose", "visitDate", "status", "plate", "phone", "remark"],
      [
        ["陈默", "南湾新材料有限公司", "星澜智造（上海）有限公司", "顾清和", "洽谈扩租", "2026-10-03", "待审核", "沪AD3821", "13817660021", "需进入 12 层，请前台核验身份证。"],
        ["苏晚", "外滩品牌部", "青禾设计工作室", "叶小满", "看方案", "2026-10-03", "已通过", "", "13916008816", "步行来访。"],
        ["周屿", "浦东新区市场监管所", "园区物业服务中心", "马俊", "例行检查", "2026-10-03", "已到访", "沪C19027", "13601880090", "已在中央大堂换证。"],
        ["韩荔", "汇川检测技术有限公司", "汇川检测技术有限公司", "裴宁", "退租交接", "2026-10-02", "已离开", "", "13764551120", "钥匙已交回秩序班。"],
        ["无名推销", "个人", "星澜智造（上海）有限公司", "顾清和", "推销门禁设备", "2026-10-01", "已拒绝", "", "13100001111", "企业明确拒绝，不要再次放行。"],
        ["林乔", "东岸半导体总部", "东岸半导体有限公司", "梁川", "内部审计", "2026-10-04", "待审核", "沪B77210", "15021998821", "预计停留一天。"],
        ["赵小宁", "浦江云算合作机房", "浦江云算科技有限公司", "沈知远", "机房参观", "2026-10-03", "已通过", "沪AF2201", "18621110028", "不得拍照。"],
      ],
    ),
  },
  {
    key: "energy",
    title: "能源监测",
    noun: "表计",
    group: "运行监测",
    path: "/energy",
    description: "电、水、冷热表计和最近读数。曲线在态势大屏的能耗监测，这里只维护台账。",
    codePrefix: "NH-202610",
    storageKey: "park-campus-energy-v1",
    nameField: "name",
    createLabel: "新建表计",
    stats: [
      { label: "异常", field: "status", equals: "异常", tone: "red" },
      { label: "离线", field: "status", equals: "离线", tone: "orange" },
      { label: "正常", field: "status", equals: "正常", tone: "green" },
      { label: "表计数", tone: "blue" },
    ],
    fields: [
      { key: "name", label: "表计名称", kind: "text", required: true, list: true, width: 180, search: true, span: 12 },
      { key: "kind", label: "类型", kind: "select", required: true, list: true, filter: true, tag: true, options: ["电表", "水表", "冷量表", "热量表"] },
      { key: "building", label: "楼宇", kind: "select", required: true, list: true, filter: true, options: buildingNames },
      { key: "location", label: "安装位置", kind: "text", required: true, list: true, search: true, span: 12 },
      { key: "reading", label: "最近读数", kind: "number", required: true, list: true, width: 120 },
      { key: "unit", label: "单位", kind: "select", required: true, options: ["kWh", "m³", "GJ"] },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["正常", "异常", "离线"] },
      { key: "readAt", label: "抄表时间", kind: "text", required: true, list: true, width: 160, placeholder: "2026-10-03 08:00" },
      { key: "owner", label: "责任人", kind: "text", required: true, search: true },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "kind", "building", "location", "reading", "unit", "status", "readAt", "owner", "remark"],
      [
        ["海纳楼总配电", "电表", "海纳楼", "B1 配电间", "128640", "kWh", "正常", "2026-10-03 08:10", "电工班·王磊", ""],
        ["海纳楼客梯回路", "电表", "海纳楼", "电梯机房", "8640", "kWh", "异常", "2026-10-03 08:12", "电工班·王磊", "负荷波动，与客梯报修同一位置。"],
        ["星河楼总水表", "水表", "星河楼", "水泵房", "3260", "m³", "正常", "2026-10-03 08:05", "给排水班·孙凯", ""],
        ["云启实验室冷量表", "冷量表", "云启楼", "5F 实验室", "412", "GJ", "正常", "2026-10-03 08:20", "暖通班·李婷", "单独结算给临港生物。"],
        ["科创中心热量表", "热量表", "科创中心", "屋顶机房", "0", "GJ", "离线", "2026-10-02 21:40", "暖通班·李婷", "通讯中断，尚未恢复。"],
        ["中轴景观水表", "水表", "园区公共区", "中轴水景", "188", "m³", "正常", "2026-10-03 07:50", "给排水班·孙凯", ""],
        ["星河楼分项电表", "电表", "星河楼", "6F 弱电间", "22190", "kWh", "正常", "2026-10-03 08:16", "弱电班·赵衡", "覆盖浦江云算机房。"],
        ["旧传达室电表", "电表", "旧传达室", "门厅", "12", "kWh", "离线", "2026-09-01 09:00", "电工班·王磊", "楼宇停用，表计封存。"],
      ],
    ),
  },
  {
    key: "security",
    title: "安防监控",
    noun: "点位",
    group: "通行安防",
    path: "/security",
    description: "视频、门禁和周界点位的在线状态。画面流暂不播放，告警记在台账里，通行大屏可看点位示意。",
    codePrefix: "AF-202610",
    storageKey: "park-campus-security-v1",
    nameField: "name",
    createLabel: "新建点位",
    stats: [
      { label: "告警", field: "status", equals: "告警", tone: "red" },
      { label: "离线", field: "status", equals: "离线", tone: "orange" },
      { label: "在线", field: "status", equals: "在线", tone: "green" },
      { label: "点位数", tone: "blue" },
    ],
    fields: [
      { key: "name", label: "点位名称", kind: "text", required: true, list: true, width: 180, search: true, span: 12 },
      { key: "building", label: "楼宇", kind: "select", required: true, list: true, filter: true, options: buildingNames },
      { key: "location", label: "位置", kind: "text", required: true, list: true, search: true },
      { key: "kind", label: "类型", kind: "select", required: true, list: true, filter: true, options: ["枪机", "球机", "门禁", "周界"] },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["在线", "离线", "告警"] },
      { key: "level", label: "关注级别", kind: "select", required: true, list: true, tag: true, width: 110, options: ["普通", "重点"] },
      { key: "owner", label: "责任班组", kind: "text", required: true, list: true, search: true },
      { key: "note", label: "最近状态", kind: "text", required: true, search: true, span: 16 },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "building", "location", "kind", "status", "level", "owner", "note", "remark"],
      [
        ["海纳楼电梯厅球机", "海纳楼", "1F 电梯厅", "球机", "告警", "重点", "秩序班·马俊", "客梯检修时段有人滞留", "与报修位置相同，回放入口尚未接通。"],
        ["海纳楼大堂枪机", "海纳楼", "1F 大堂", "枪机", "在线", "普通", "秩序班·马俊", "画面正常", ""],
        ["星河楼门禁", "星河楼", "1F 门厅", "门禁", "在线", "重点", "弱电班·赵衡", "通行正常", ""],
        ["云启北侧周界", "云启楼", "北侧围墙", "周界", "在线", "重点", "秩序班·马俊", "无告警", ""],
        ["科创车库枪机", "科创中心", "B1 车道", "枪机", "离线", "普通", "弱电班·赵衡", "夜间掉线", "已派弱电班查看交换机。"],
        ["中轴广场球机", "园区公共区", "中轴广场", "球机", "在线", "普通", "秩序班·马俊", "正常", ""],
        ["旧传达室门禁", "旧传达室", "入口", "门禁", "离线", "普通", "秩序班·马俊", "点位停用", "不再纳入巡检。"],
      ],
    ),
  },
  {
    key: "notices",
    title: "通知公告",
    noun: "公告",
    group: "园区服务",
    path: "/notices",
    description: "面向企业和物业人员发布公告、保存草稿和设置置顶。",
    codePrefix: "GG-202610",
    storageKey: "park-campus-notices-v1",
    nameField: "title",
    createLabel: "新建公告",
    stats: [
      { label: "已发布", field: "status", equals: "已发布", tone: "green" },
      { label: "草稿", field: "status", equals: "草稿", tone: "blue" },
      { label: "置顶", field: "pinned", equals: "是", tone: "orange" },
      { label: "公告数", tone: "purple" },
    ],
    fields: [
      { key: "title", label: "标题", kind: "text", required: true, list: true, width: 240, search: true, span: 16 },
      { key: "scope", label: "阅读范围", kind: "select", required: true, list: true, filter: true, options: ["全体在园人员", "在园企业", "物业内部"] },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["草稿", "已发布", "已下线"] },
      { key: "pinned", label: "置顶", kind: "select", required: true, list: true, filter: true, tag: true, width: 90, options: ["否", "是"] },
      { key: "author", label: "发布人", kind: "text", required: true, list: true, search: true },
      { key: "publishAt", label: "发布日期", kind: "date", required: true, list: true, width: 120 },
      { key: "content", label: "正文", kind: "textarea", required: true, placeholder: "写清时间、地点和需要企业配合的事项" },
    ],
    seed: rows(
      ["title", "scope", "status", "pinned", "author", "publishAt", "content"],
      [
        ["海纳楼客梯检修通知", "全体在园人员", "已发布", "是", "周启明", "2026-10-02", "海纳楼客梯今日继续检修，请改乘货梯。企业报修仍在处理中，恢复后会再发公告。"],
        ["十月物业费缴纳提醒", "在园企业", "已发布", "是", "陈予安", "2026-10-01", "请于账单到期日前完成缴纳。逾期记录可在物业缴费中查看。"],
        ["秋季消防演练预告", "全体在园人员", "草稿", "否", "马俊", "2026-10-08", "计划于 10 月 18 日下午进行疏散演练，草稿待运营部确认集合点。"],
        ["中秋园区活动回顾", "全体在园人员", "已下线", "否", "林知夏", "2026-09-20", "活动已结束，公告下线，仅作档案保留。"],
        ["访客预约改为提前一天", "在园企业", "已发布", "否", "林知夏", "2026-09-28", "机房、实验室来访请至少提前一个工作日在访客通行中登记。"],
        ["裙房装修围挡说明", "物业内部", "草稿", "否", "周启明", "2026-10-03", "海纳楼裙房东侧围挡保留到 10 月 18 日，秩序班不要引导访客穿行。"],
      ],
    ),
  },
  {
    key: "users",
    title: "用户管理",
    noun: "用户",
    group: "系统设置",
    path: "/system/users",
    description: "运营账号与组织归属。演示登录仍使用固定账号，此台账只保存在本机。",
    codePrefix: "YH-202610",
    storageKey: "park-campus-users-v1",
    nameField: "name",
    createLabel: "新建用户",
    stats: [
      { label: "启用", field: "status", equals: "启用", tone: "green" },
      { label: "停用", field: "status", equals: "停用", tone: "red" },
      { label: "管理员", field: "role", equals: "园区管理员", tone: "blue" },
      { label: "用户数", tone: "purple" },
    ],
    fields: [
      { key: "name", label: "姓名", kind: "text", required: true, list: true, width: 120, search: true },
      { key: "username", label: "账号", kind: "text", required: true, list: true, search: true },
      { key: "role", label: "角色", kind: "select", required: true, list: true, filter: true, options: ["园区管理员", "物业主管", "收费专员", "安保班长", "弱电班长", "只读账号"] },
      { key: "org", label: "组织", kind: "text", required: true, list: true, search: true },
      { key: "phone", label: "手机", kind: "text", required: true, search: true },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["启用", "停用"] },
      { key: "lastLogin", label: "最近登录", kind: "text", list: true, width: 160, placeholder: "2026-10-03 08:06" },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "username", "role", "org", "phone", "status", "lastLogin", "remark"],
      [
        ["林知夏", "admin", "园区管理员", "园区运营部", "13801770021", "启用", "2026-10-03 08:06", "演示账号，登录页仍可使用。"],
        ["周启明", "wuye", "物业主管", "物业服务部", "13916330086", "启用", "2026-10-03 07:48", "演示账号。"],
        ["陈予安", "caiwu", "收费专员", "财务管理部", "13601880045", "启用", "2026-10-02 18:12", "演示账号。"],
        ["马俊", "majun", "安保班长", "秩序维护部", "13761660019", "启用", "2026-10-03 07:30", "负责访客核验与点位巡查。"],
        ["赵衡", "zhaoheng", "弱电班长", "弱电班", "15021990028", "启用", "2026-10-01 16:40", "负责门禁和表计通讯。"],
        ["韩朔", "hanshuo", "只读账号", "园区运营部", "13166220074", "停用", "2026-08-19 11:02", "已离职，账号停用。"],
      ],
    ),
  },
  {
    key: "roles",
    title: "角色管理",
    noun: "角色",
    group: "系统设置",
    path: "/system/roles",
    description: "角色、数据范围和权限摘要。不会改变当前登录权限。",
    codePrefix: "JS-202610",
    storageKey: "park-campus-roles-v1",
    nameField: "name",
    createLabel: "新建角色",
    stats: [
      { label: "启用", field: "status", equals: "启用", tone: "green" },
      { label: "停用", field: "status", equals: "停用", tone: "red" },
      { label: "全园区", field: "scope", equals: "全园区", tone: "blue" },
      { label: "角色数", tone: "purple" },
    ],
    fields: [
      { key: "name", label: "角色名称", kind: "text", required: true, list: true, width: 160, search: true },
      { key: "scope", label: "数据范围", kind: "select", required: true, list: true, filter: true, options: ["全园区", "本部门", "本人"] },
      { key: "members", label: "成员数", kind: "number", required: true, list: true, suffix: "人", width: 110 },
      { key: "perms", label: "权限摘要", kind: "text", required: true, list: true, width: 280, search: true, span: 16 },
      { key: "status", label: "状态", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["启用", "停用"] },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: rows(
      ["name", "scope", "members", "perms", "status", "remark"],
      [
        ["园区管理员", "全园区", "1", "企业、合同、公告和系统台账", "启用", "对应演示账号 admin。"],
        ["物业主管", "本部门", "1", "报修、楼宇、房间和公告", "启用", "对应演示账号 wuye。"],
        ["收费专员", "本部门", "1", "账单、合同金额和催缴", "启用", "对应演示账号 caiwu。"],
        ["安保班长", "本部门", "1", "访客审核和监控点位", "启用", ""],
        ["弱电班长", "本部门", "1", "表计和门禁点位", "启用", ""],
        ["只读账号", "本人", "1", "只查看台账", "停用", "离职人员使用，现已停用。"],
      ],
    ),
  },
  {
    key: "menus",
    title: "菜单管理",
    noun: "菜单",
    group: "系统设置",
    path: "/system/menus",
    description: "菜单与路由对照。修改只写入本机台账，不会改左侧导航。",
    codePrefix: "CD-202610",
    storageKey: "park-campus-menus-v1",
    nameField: "name",
    createLabel: "新建菜单",
    stats: [
      { label: "显示", field: "visible", equals: "显示", tone: "green" },
      { label: "隐藏", field: "visible", equals: "隐藏", tone: "red" },
      { label: "系统设置", field: "group", equals: "系统设置", tone: "blue" },
      { label: "菜单数", tone: "purple" },
    ],
    fields: [
      { key: "name", label: "菜单名称", kind: "text", required: true, list: true, width: 160, search: true },
      { key: "route", label: "路由", kind: "text", required: true, list: true, width: 220, search: true },
      { key: "group", label: "分组", kind: "select", required: true, list: true, filter: true, options: menuGroups },
      { key: "sort", label: "排序", kind: "number", required: true, list: true, width: 90 },
      { key: "visible", label: "显示", kind: "select", required: true, list: true, filter: true, tag: true, width: 100, options: ["显示", "隐藏"] },
      { key: "remark", label: "备注", kind: "textarea" },
    ],
    seed: menuSeed(),
  },
];

const byKey = new Map(resources.map((item) => [item.key, item]));

export function resourceByKey(key: string) {
  return byKey.get(key);
}
